Small installation fixes
vanaoff/move-to-next-monitor pull request #1
Opened 2018-05-05 08:17 UTC by davla

- `/bin/env`  has been moved to `/usr.bin/env`. Fixed inconsistency between `install.sh` and the python script.
- Added fix for system in which the default `python` interpreter is still version 2.

2018-05-06 09:17 UTC, vanaoff requested changes
Hey, thanks for pull request. Maybe it would be sufficient to enforce `python3` in default instead of sedding changes into file. Ideas?

2018-05-07 17:35 UTC, davla commented
Well, that would affect the whole system, potentially breaking other packages. If you meant the script to be used only on Manjaro and other Arch-based then feel free to discard my pull-request.

2018-05-07 18:06 UTC, vanaoff commented
Hey, sorry, it was not very clear. I didn't intend to make python3 default in system - which makes no sense at all. I meant to put to the shebang line `#!/usr/bin/env python3` directly. This should work in all cases.

2018-05-08 10:26 UTC, davla commented
In my system `/usr/bin/env python` defaults to `python2.7`, so I cannot test. But if `/usr/bin/env python2` defaults to `python2.7`, so I guess you're right. I implemented the changes.

2018-05-09 05:53 UTC, merged